# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Analyze_AllPUDDatasets.py
# Created on: 2016-09-08 11:59:29.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Set the necessary product code
import arceditor


# Import arcpy module
import arcpy


# Local variables:
EDIT_PUD_WATER = "Database Connections\\pud@atlas-edit.sde\\EDIT.PUD.WATER"
EDIT_PUD_WATER__2_ = EDIT_PUD_WATER
EDIT_PUD_CATHODIC_PROTECTION = "Database Connections\\ad@atlas-edit.sde\\EDIT.PUD.CATHODIC_PROTECTION"
EDIT_PUD_CATHODIC_PROTECTION__3_ = EDIT_PUD_CATHODIC_PROTECTION
EDIT_PUD_MISC = "Database Connections\\ad@atlas-edit.sde\\EDIT.PUD.MISC"
EDIT_PUD_MISC__3_ = EDIT_PUD_MISC
EDIT_PUD_RECYCLED = "Database Connections\\ad@atlas-edit.sde\\EDIT.PUD.RECYCLED"
EDIT_PUD_RECYCLED__3_ = EDIT_PUD_RECYCLED
EDIT_PUD_SEWER = "Database Connections\\ad@atlas-edit.sde\\EDIT.PUD.SEWER"
EDIT_PUD_SEWER__3_ = EDIT_PUD_SEWER
EDIT_PUD_WATER__3_ = "Database Connections\\ad@atlas-edit.sde\\EDIT.PUD.WATER"
EDIT_PUD_WATER__5_ = EDIT_PUD_WATER__3_

# Process: Analyze
arcpy.Analyze_management(EDIT_PUD_WATER, "BUSINESS;FEATURE")

# Process: Analyze (2)
arcpy.Analyze_management(EDIT_PUD_CATHODIC_PROTECTION, "BUSINESS;FEATURE")

# Process: Analyze (3)
arcpy.Analyze_management(EDIT_PUD_MISC, "BUSINESS;FEATURE")

# Process: Analyze (4)
arcpy.Analyze_management(EDIT_PUD_RECYCLED, "BUSINESS;FEATURE")

# Process: Analyze (5)
arcpy.Analyze_management(EDIT_PUD_SEWER, "BUSINESS;FEATURE")

# Process: Analyze (6)
arcpy.Analyze_management(EDIT_PUD_WATER__3_, "BUSINESS;FEATURE")

