# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Compress.py
# Created on: 2016-09-08 11:37:48.00000
#   (generated by ArcGIS/ModelBuilder)
# Description:
# ---------------------------------------------------------------------------


# Import arcpy module
import arcpy


# Local variables:
pudConnectionFile = "Database Connections\\zAtlas-editdev.sde (SDE ADMIN).sde"

# Process: Compress
arcpy.Compress_management(pudConnectionFile)

