# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Rebuild_Indexes.py
# Created on: 2016-09-08 11:58:33.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Set the necessary product code
import arceditor


# Import arcpy module
import arcpy


# Local variables:
ad_atlas-edit_sde = "Database Connections\\ad@atlas-edit.sde"
ad_atlas-edit_sde__2_ = ad_atlas-edit_sde

# Process: Rebuild Indexes
arcpy.RebuildIndexes_management(ad_atlas-edit_sde, "SYSTEM", "", "ALL")

